services:
  api:
    container_name: api
    image: api
    build:
      context: .
      target: builder
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev
    restart: always
    networks:
      - network
    ports:
      - 8000:3000
    depends_on:
      - redis

  redis:
    image: redis
    container_name: cache
    networks:
      - network
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  network:

volumes:
  data:
  redis:
    driver: local
